/**
 * @vida/database - Shared database types and schemas for the VIDA ecosystem.
 *
 * @example
 * import type { Profile, Transaction, MedicalProfile } from "@vida/database";
 * import type { Account } from "@vida/database/types/money";
 */

// Re-export all types from the types barrel
export type {
  // Common
  UUID,
  ISODateTime,
  ISODate,
  BaseRecord,
  Currency,
  AppTier,
  AppSlug,
  User,
  Profile,
  NotificationPreferences,
  FamilyRole,
  FamilyGroup,
  FamilyGroupSettings,
  FamilyMember,

  // Money (VIDA Dinheiro)
  AccountType,
  Account,
  CategoryType,
  Category,
  TransactionType,
  TransactionStatus,
  Transaction,
  RecurringRule,
  BudgetPeriod,
  Budget,
  GoalStatus,
  Goal,
  Fund,
  XitiqueStatus,
  XitiqueGroup,
  XitiqueMember,
  DebtDirection,
  DebtStatus,
  DebtRecord,
  DebtPayment,

  // Home (VIDA Lar)
  Zone,
  InventoryCondition,
  InventoryItem,
  ShoppingList,
  ShoppingListItem,
  MaintenancePriority,
  MaintenanceStatus,
  MaintenanceTask,
  EmploymentType,
  EmployeeRole,
  DomesticEmployee,
  WorkSchedule,
  EmergencyContact,
  MealType,
  MealPlan,
  MealIngredient,
  RoutineFrequency,
  Routine,

  // Health (VIDA Saude)
  BloodType,
  MedicalProfile,
  MedicationFrequency,
  MedicationStatus,
  Medication,
  MedicationSchedule,
  AppointmentStatus,
  AppointmentType,
  Appointment,
  Vaccination,
  ProviderSpecialty,
  HealthProvider,
  ProviderWorkingHours,
  MetricType,
  HealthMetric,
  ClaimStatus,
  InsuranceClaim,

  // Family (VIDA Familia)
  EventType,
  EventRecurrence,
  CalendarEvent,
  EventReminder,
  TaskPriority,
  TaskStatus,
  FamilyTask,
  Photo,
  PhotoAlbum,
  MilestoneCategory,
  Milestone,
  MilestoneReaction,
  MessageType,
  ChatMessage,
  MessageReadReceipt,
  MessageReaction,
  FamilyGoalStatus,
  FamilyGoalCategory,
  FamilyGoal,
  GoalMilestone,
} from "./types/index";
